name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Create output directory
        run: mkdir -p dist

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: paollarsp
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: List output files
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
