name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - name: Criar diretório dist
        run: mkdir -p dist

      - name: Gerar animação snake
        uses: Platane/snk@v3
        with:
          github_user_name: paollarsp
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Listar arquivos no diretório dist
        run: ls -la dist

      - name: Deploy para GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
